language: objective-c
matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: osx10.11
      rvm: system
    - env: OSX=10.10
      os: osx
      osx_image: xcode7
      rvm: system
    - env: OSX=10.9
      os: osx
      osx_image: beta-xcode6.2
      rvm: system

before_install:
  - if [ -f ".git/shallow" ]; then travis_retry git fetch --unshallow; fi
  - sudo rm -rf $(brew --repo)/Library/Taps/domt4/homebrew-crypto/
  - sudo chown -R $USER $(brew --repo)
  - brew update
  - mkdir -p $(brew --repo)/Library/Taps/domt4/
  - ln -sf $PWD $(brew --repo)/Library/Taps/domt4/homebrew-crypto/
  - cd $(brew --repo)/Library/Taps/domt4/homebrew-crypto/
  - export TRAVIS_BUILD_DIR="$(brew --repo)/Library/Taps/domt4/homebrew-crypto"
  - env | grep TRAVIS_

script:
  - brew test-bot --tap=domt4/crypto

notifications:
  email: false
